/* AUTO-GENERATED by src/tools/bakereads.ts from money.json - do not edit by hand.
 * Measured opponent reads: 412,750 sampled decisions over 25,000 hands of run "run-money4".
 *   dangerSafe: P(this discard deals in) keyed "<class>|<turn>|<fresh|seen>" - a tile already on the
 *     floor is far safer, which is the whole reason the discard pool is worth reading.
 *   dangerWall: the same, split again by whether every RUN that could contain the tile is already
 *     impossible because all four copies of a neighbour it needs are accounted for. Measured at
 *     three to five times safer, every cell, which is the tactics book's `no_chance_tiles`.
 *   ready: P(an opponent is ready) keyed "<exposed melds>|<turn>" - how much to fear them at all.
 */
export const READS = {
  dangerSafe: {"simple|0|fresh":0.0000967,"terminal|0|fresh":0.0000179,"honour|0|fresh":0,"honour|0|seen":0,"terminal|0|seen":0,"simple|0|seen":0.000186,"terminal|10|fresh":0.000801,"simple|10|fresh":0.00146,"honour|10|fresh":0.000259,"honour|10|seen":0.0000342,"terminal|10|seen":0.000482,"simple|10|seen":0.00101,"simple|20|fresh":0.0065,"simple|20|seen":0.00376,"honour|20|fresh":0.00116,"terminal|20|seen":0.00221,"terminal|20|fresh":0.00367,"honour|20|seen":0.000113,"terminal|30|seen":0.00379,"honour|30|seen":0.000338,"simple|30|fresh":0.0123,"simple|30|seen":0.00722,"honour|30|fresh":0.00216,"terminal|30|fresh":0.00783,"honour|40|seen":0.000618,"simple|40|fresh":0.0164,"simple|40|seen":0.00986,"terminal|40|seen":0.00566,"honour|40|fresh":0.00366,"terminal|40|fresh":0.0105,"honour|50|seen":0.0007,"simple|50|fresh":0.0173,"simple|50|seen":0.00884,"terminal|50|seen":0.00411,"honour|50|fresh":0.00691,"simple|60|seen":0.00676,"terminal|60|seen":0.00392,"honour|60|seen":0.0012,"simple|60|fresh":0.0148,"honour|60|fresh":0.00858,"terminal|50|fresh":0.0104,"terminal|60|fresh":0.0116} as Record<string, number>,
  danger: {"simple|0":0.000099,"terminal|0":0.000017,"honour|0":0,"terminal|10":0.000728,"simple|10":0.0014,"honour|10":0.000176,"simple|20":0.00579,"honour|20":0.000618,"terminal|20":0.00308,"terminal|30":0.00572,"honour|30":0.00106,"simple|30":0.0104,"honour|40":0.00158,"simple|40":0.0132,"terminal|40":0.00746,"honour|50":0.00223,"simple|50":0.0121,"terminal|50":0.00587,"simple|60":0.00872,"terminal|60":0.00521,"honour|60":0.00229} as Record<string, number>,
  dangerWall: {"simple|0|fresh|open":0.0000967,"terminal|0|fresh|open":0.0000179,"terminal|0|seen|open":0,"simple|0|seen|open":0.000186,"terminal|10|fresh|open":0.000805,"simple|10|fresh|open":0.00146,"terminal|10|seen|open":0.000464,"simple|10|seen|open":0.00101,"simple|20|fresh|open":0.00651,"simple|20|seen|open":0.00378,"terminal|20|seen|open":0.00225,"terminal|20|fresh|open":0.00374,"terminal|30|seen|open":0.0039,"simple|30|fresh|open":0.0123,"simple|30|seen|open":0.00728,"terminal|30|fresh|open":0.00811,"simple|40|fresh|open":0.0166,"simple|40|seen|open":0.01,"terminal|40|seen|open":0.00626,"terminal|40|fresh|open":0.0112,"simple|50|fresh|open":0.0177,"simple|50|seen|open":0.00916,"terminal|50|seen|open":0.00492,"terminal|50|seen|walled":0.000907,"simple|60|seen|open":0.00737,"terminal|60|seen|walled":0.00239,"simple|60|fresh|open":0.0152,"terminal|60|seen|open":0.00495,"simple|60|seen|walled":0.00366,"simple|40|fresh|walled":0.00447,"simple|50|seen|walled":0.00256,"terminal|10|fresh|walled":0,"simple|10|seen|walled":0,"terminal|50|fresh|open":0.0107,"terminal|60|fresh|open":0.0138,"terminal|30|seen|walled":0.00175,"terminal|40|seen|walled":0.000628,"terminal|50|fresh|walled":0.0091,"terminal|60|fresh|walled":0.00768,"simple|30|fresh|walled":0.0039,"simple|50|fresh|walled":0.0104,"simple|60|fresh|walled":0.0122,"simple|30|seen|walled":0,"simple|40|seen|walled":0.00143,"terminal|20|seen|walled":0.000839,"simple|10|fresh|walled":0,"terminal|30|fresh|walled":0.00208,"terminal|40|fresh|walled":0.00397,"terminal|10|seen|walled":0.00313,"simple|20|fresh|walled":0.00119,"simple|20|seen|walled":0,"terminal|20|fresh|walled":0,"terminal|0|fresh|walled":0,"simple|0|fresh|walled":0} as Record<string, number>,
  ready: {"0|0":0.00293,"0|10":0.024,"1|10":0.061,"0|20":0.0651,"1|20":0.125,"1|30":0.169,"0|30":0.0982,"1|40":0.185,"2|40":0.286,"1|50":0.16,"2|50":0.248,"1|60":0.111,"2|60":0.174,"3|60":0.387,"1|0":0.0189,"0|40":0.111,"0|50":0.0898,"2|20":0.242,"2|30":0.284,"3|40":0.505,"3|50":0.451,"2|0":0.0724,"2|10":0.167,"3|10":0.393,"0|60":0.0662,"3|20":0.523,"3|30":0.526} as Record<string, number>
} as const;

/**
 * Turning the measured reads into numbers, in one place.
 *
 * Both the book coach (`rank.ts`) and the learned model (`policy.ts`) need these, and they must
 * agree: the coach prices danger into its ranking, and the model takes the same quantities as
 * features. Two copies of this arithmetic would drift.
 */
import { isHonour, isJoker, isSuited, isTerminal, suitOf, type TileKind } from 'sg-mahjong-engine';

/** The shape of a reads table, so an alternative one can be played against the shipped one.
 *  `Context.reads` carries it; everything defaults to READS, which is what the coach uses. */
export interface ReadsTables { dangerSafe: Record<string, number>; danger: Record<string, number>; ready: Record<string, number>; dangerWall?: Record<string, number> }

const bucket = (turn: number) => Math.max(0, Math.min(60, Math.round(turn / 10) * 10));
const tileClass = (k: TileKind) => (isHonour(k) ? 'honour' : isTerminal(k) ? 'terminal' : 'simple');

/**
 * Is every RUN that could contain this tile already impossible?
 *
 * A tile completes a run three ways - bottom, middle, top - and each needs two specific neighbours.
 * When all four copies of one of a pair are accounted for, that way is dead; when all three are
 * dead the tile can only be hit by a pair wait or a lone tile wait. Measured at three to five times
 * safer in every cell of `dangerWall`.
 *
 * `accounted[k]` is how many copies of kind k the player can SEE plus how many they hold - the same
 * count the measurement used, so the table and the lookup agree about what "gone" means.
 */
export function walled(k: TileKind, accounted: ArrayLike<number>): boolean {
  if (!isSuited(k)) return false;                       // honours are never part of a run
  const r = (k % 9) + 1, base = k - (r - 1);
  const alive = (rank: number) => (accounted[base + rank - 1] ?? 0) < 4;
  const pairs: [number, number][] = [[r - 2, r - 1], [r - 1, r + 1], [r + 1, r + 2]];
  return !pairs.some(([a, b]) => a >= 1 && a <= 9 && b >= 1 && b <= 9 && alive(a) && alive(b));
}

/** P(throwing this tile deals in), given how late it is and whether the tile is already on the floor.
 *  Pass `isWalled` to use the measured discount for a tile no run can still be waiting on; without
 *  it the answer is the coarser one the coach used before, which is what makes the two comparable. */
export function dealInChance(k: TileKind, playerTurns: number, seenCopies: number, R: ReadsTables = READS, isWalled = false): number {
  if (isJoker(k)) return 0;
  const t = bucket(playerTurns);
  const fresh = seenCopies === 0 ? 'fresh' : 'seen';
  if (isWalled) {
    const w = R.dangerWall?.[`${tileClass(k)}|${t}|${fresh}|walled`];
    if (w !== undefined) return w;                      // fall through when that cell was too thin to measure
  }
  return R.dangerSafe[`${tileClass(k)}|${t}|${fresh}`] ?? R.danger[`${tileClass(k)}|${t}`] ?? 0;
}

/**
 * How ready this table looks against a typical one at the same turn. 1 means average; a table with
 * three exposed sets everywhere runs high, a quiet one low. Clamped so one strange seat cannot
 * dominate the estimate.
 */
export function threatScale(opponentMelds: readonly number[] | undefined, playerTurns: number, R: ReadsTables = READS): number {
  if (!opponentMelds?.length) return 1;
  const t = bucket(playerTurns);
  const readyOf = (m: number) => R.ready[`${Math.max(0, Math.min(3, m))}|${t}`] ?? 0;
  const here = opponentMelds.reduce((a, m) => a + readyOf(m), 0) / opponentMelds.length;
  const typical = readyOf(0) * 0.55 + readyOf(1) * 0.3 + readyOf(2) * 0.12 + readyOf(3) * 0.03;
  return typical > 1e-9 ? Math.max(0.25, Math.min(4, here / typical)) : 1;
}

/**
 * The chance the MOST advanced opponent is ready, straight off the measured table.
 *
 * `threatScale` answers "is this table busier than usual", which prices a discard. Folding needs a
 * different question - "is somebody actually about to win" - and that is an absolute probability,
 * not a ratio. Three exposed sets at turn 40 is 39.5%; nothing exposed at turn 20 is 2.0%.
 */
export function maxReadyChance(opponentMelds: readonly number[] | undefined, playerTurns: number, R: ReadsTables = READS): number {
  if (!opponentMelds?.length) return 0;
  const t = bucket(playerTurns);
  let mx = 0;
  for (const m of opponentMelds) mx = Math.max(mx, R.ready[`${Math.max(0, Math.min(3, m))}|${t}`] ?? 0);
  return mx;
}

/** What one other seat has shown the table: the tiles in their exposed sets, and what they threw. */
export interface OpponentPublic {
  /** how to name them in advice - their wind, usually */
  label?: string;
  melds: readonly (readonly TileKind[])[];
  discards: readonly TileKind[];
}

/**
 * Which suit this seat is visibly collecting, from public information only.
 *
 * The tactics book calls this the strongest single read available, and it is the one thing the
 * coach's threat model cannot see: that model is a COUNT of exposed sets, so a dragon pong and a
 * chow of 3-4-5 are the same input to it.
 *
 * Two exposed sets in one suit is not on its own a tell - anyone can be dealt two. The second half
 * is what makes it: a player assembling a suit does not throw that suit away. Honour melds do not
 * break the pattern, because Half-Color is one suit plus honours.
 *
 * MEASURED on 25,000 hands the coach played against itself: a seat flagged this way really is
 * building that suit about half the time, and a tile in it deals in to them at twice the rate of a
 * tile outside it, rising to five times late in the hand. On the RECORDED runs it measures the
 * other way round, because the bots that played them have no colour target at all - 1.3% of their
 * wins are colour hands against the coach's 32% - so there is nothing there to find and only the
 * scarcity of a melded suit is left. See FINDINGS.
 *
 * This is REPORTED, never priced. Played as a discard weighting it is worth -0.034 +/- 0.057 chips
 * a game over 16,000 paired deals, which is nothing; the coach already prices danger on every
 * throw and is close to the best tile anyway. A person reading the advice does not, which is why
 * the same fact is worth saying out loud and not worth scoring with.
 */
export function collectingSuit(o: OpponentPublic): 'wan' | 'tong' | 'sok' | null {
  const suited = o.melds.filter((m) => m.length > 0 && isSuited(m[0]!));
  if (suited.length < 2) return null;
  const s = suitOf(suited[0]![0]!);
  if (!s || !suited.every((m) => suitOf(m[0]!) === s)) return null;
  if (o.discards.filter((k) => suitOf(k) === s).length > 1) return null;
  return s;
}

/** Every seat that looks like it is collecting a suit, with the suit. Empty when nothing shows. */
export function suitWatch(opponents: readonly OpponentPublic[] | undefined): { label: string; suit: string }[] {
  const out: { label: string; suit: string }[] = [];
  for (const o of opponents ?? []) { const s = collectingSuit(o); if (s) out.push({ label: o.label ?? 'a player', suit: s }); }
  return out;
}
