/**
 * Bake the study's value tables into `solver/src/tables.ts`, with our measured row corrections
 * applied on the way through.
 *
 *   node node_modules/tsx/dist/cli.mjs src/tools/baketables.ts            # study's numbers, corrected
 *   node node_modules/tsx/dist/cli.mjs src/tools/baketables.ts --plain    # study's numbers, untouched
 *
 * `tables.ts` carried an "AUTO-GENERATED" header with no generator behind it, exactly as `reads.ts`
 * did before `bakereads.ts` was written. This is that generator.
 *
 * IT ALWAYS READS THE PRISTINE STUDY SNAPSHOT, never the current `tables.ts`. That is what makes
 * running it twice the same as running it once. If it read its own output the corrections would
 * compound quietly, and the coach would drift a little further from the book every time somebody
 * regenerated - which is the kind of fault that is invisible until a number stops reproducing.
 *
 * WHAT THE CORRECTION IS. Our own 150,000 recorded hands agree with the study about the order of
 * hands inside one plan at one turn, at an R-squared of 0.86 to 1.00. Where they disagree is about
 * how much one plan's spread is worth against another's: measured row by row, the cheap hand needs
 * a scale near 1.9 and a late half-colour hand near 5.5. `datagen/src/valuerows.ts` measures those
 * slopes and writes the corrected table set this reads, at the gain that leaves the coach as
 * decisive as it was.
 *
 * Worth +0.200 +/- 0.041 chips a game over 64,000 paired deals on eight ranges named before each
 * run, positive on all eight. The control is a flat multiplier matched to the same decisiveness,
 * which loses 0.163, so the re-weighting is doing the work rather than the flattening. It is the
 * second change ever shipped to the coach and about eleven times the size of the first. See
 * FINDINGS, "Our own value tables lose".
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const args = process.argv.slice(2);
const plain = args.includes('--plain');
const at = (n: string, d: string) => { const i = args.indexOf(`--${n}`); return i >= 0 ? (args[i + 1] ?? d) : d; };
const studyPath = at('study', '../knowledge/sources/tables.study.json');
const fittedPath = at('fitted', '../knowledge/sources/fitted/tables-committed-g1.30.json');
const outPath = at('out', 'src/tables.ts');

const study = (JSON.parse(readFileSync(resolve(studyPath), 'utf8')) as { TABLES: Record<string, unknown> }).TABLES;
const tables = plain ? study : (JSON.parse(readFileSync(resolve(fittedPath), 'utf8')) as Record<string, unknown>);

// A corrected set must differ from the study ONLY in numbers. A changed key would silently change
// how `lookup` interpolates between neighbouring points, so the coach would be reading a different
// curve rather than different values on the same curve.
function sameShape(a: unknown, b: unknown, path = ''): string[] {
  if (typeof a === 'object' && a !== null && typeof b === 'object' && b !== null) {
    const ka = Object.keys(a as object), kb = Object.keys(b as object);
    const bad: string[] = [];
    for (const k of ka) if (!kb.includes(k)) bad.push(`${path}/${k} missing from the fitted set`);
    for (const k of kb) if (!ka.includes(k)) bad.push(`${path}/${k} is not in the study's tables`);
    for (const k of ka) if (kb.includes(k)) bad.push(...sameShape((a as Record<string, unknown>)[k], (b as Record<string, unknown>)[k], `${path}/${k}`));
    return bad;
  }
  if (typeof a !== typeof b) return [`${path} changed type`];
  return [];
}
if (!plain) {
  const bad = sameShape(study, tables);
  if (bad.length) { console.error(`the fitted tables do not have the study's shape:\n  ${bad.join('\n  ')}`); process.exit(1); }
}

let changed = 0, total = 0;
(function count(a: unknown, b: unknown): void {
  if (typeof a === 'object' && a !== null) { for (const k of Object.keys(a as object)) count((a as Record<string, unknown>)[k], (b as Record<string, unknown>)[k]); return; }
  if (typeof a === 'number') { total++; if (a !== b) changed++; }
})(study, tables);

const provenance = plain
  ? ` * The study author's numbers exactly as published, with no correction applied.`
  : ` * The study author's numbers with our measured row corrections applied (${fittedPath.split('/').pop()}).
 * ${changed} of ${total} numbers differ from the study's own. Each row is multiplied by one constant
 * measured from 150,000 of our recorded hands, so the ordering inside a row is the study's and only
 * the weight of one plan against another is ours. Worth +0.200 +/- 0.041 chips a game over 64,000
 * paired deals on eight ranges named in advance, positive on all eight, against a flat multiplier
 * matched to the same decisiveness that loses 0.163. See FINDINGS.md, "Our own value tables lose".`;

const header = `/* AUTO-GENERATED by src/tools/baketables.ts - do not edit by hand.
 * Chips-per-game and win-chance tables from "A Data Analytic Evaluation of Singapore Mahjong".
 * Keys: evaluator value (or All-Pong "T:P" ratio) -> chips / chance. Rows at Player Turns 0 / 20 / 40.
${provenance}
 *
 * The pristine study snapshot is ${studyPath.split('/').slice(-2).join('/')} and the generator always reads it rather
 * than this file, so regenerating is idempotent however many times it runs.
 */
export type Row = Record<string, number>;
export type ByTurn = Record<number, Row>;
export const TABLES = ${JSON.stringify(tables, null, 1)} as const;
`;

writeFileSync(resolve(outPath), header);
console.log(`${outPath} written from ${studyPath}${plain ? '' : ` corrected by ${fittedPath}`}`);
console.log(`${changed} of ${total} numbers differ from the study's own.`);
