/**
 * Bake the measured reads table into `solver/src/reads.ts`.
 *
 *   ./node_modules/.bin/tsx src/tools/bakereads.ts ../web/public/reads/money.json
 *
 * `reads.ts` carried an "AUTO-GENERATED" header for weeks with no generator behind it - somebody
 * pasted the numbers by hand. This is that generator, so the header is true and a regenerated
 * table is one command rather than a careful copy-paste.
 *
 * The solver ships the table as a constant rather than fetching JSON because the same numbers have
 * to be available to the browser build, the simulator and the evaluator without a file read.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const src = process.argv[2] ?? '../web/public/reads/money.json';
const out = process.argv[3] ?? 'src/reads.ts';
interface Cell { p: number; n: number }
const j = JSON.parse(readFileSync(resolve(src), 'utf8')) as {
  run: string; hands: number; sampled: number;
  dangerSafe: Record<string, Cell>; danger: Record<string, Cell>; ready: Record<string, Cell>; dangerWall?: Record<string, Cell>;
};

const round = (x: number) => Number(x.toPrecision(3));
const line = (t: Record<string, Cell>) => JSON.stringify(Object.fromEntries(Object.entries(t).map(([k, c]) => [k, round(c.p)])));

const header = `/* AUTO-GENERATED by src/tools/bakereads.ts from ${src.split('/').pop()} - do not edit by hand.
 * Measured opponent reads: ${j.sampled.toLocaleString('en-GB')} sampled decisions over ${j.hands.toLocaleString('en-GB')} hands of run "${j.run}".
 *   dangerSafe: P(this discard deals in) keyed "<class>|<turn>|<fresh|seen>" - a tile already on the
 *     floor is far safer, which is the whole reason the discard pool is worth reading.
 *   dangerWall: the same, split again by whether every RUN that could contain the tile is already
 *     impossible because all four copies of a neighbour it needs are accounted for. Measured at
 *     three to five times safer, every cell, which is the tactics book's \`no_chance_tiles\`.
 *   ready: P(an opponent is ready) keyed "<exposed melds>|<turn>" - how much to fear them at all.
 */`;

const body = `export const READS = {
  dangerSafe: ${line(j.dangerSafe)} as Record<string, number>,
  danger: ${line(j.danger)} as Record<string, number>,
  dangerWall: ${line(j.dangerWall ?? {})} as Record<string, number>,
  ready: ${line(j.ready)} as Record<string, number>
} as const;`;

const current = readFileSync(resolve(out), 'utf8');
const rest = current.slice(current.indexOf('\n/**\n * Turning the measured reads'));
writeFileSync(resolve(out), `${header}\n${body}\n${rest}`);
console.log(`baked ${Object.keys(j.dangerSafe).length} dangerSafe + ${Object.keys(j.dangerWall ?? {}).length} dangerWall + ${Object.keys(j.ready).length} ready cells from ${j.run} -> ${out}`);
