/**
 * Find the game that loses a tile. tsx src/leakhunt.ts [games]
 *
 * `runSim` asserts every game accounts for all 148 tiles. A coach-vs-coach run trips it, which
 * means either a bot returned something that is not in its hand or the engine drops a tile on some
 * rare path. Either way it is worth a name and a seed rather than a shrug - the datasets were
 * generated by this engine.
 */
import { Wall, playGame, kindOf, makeRng, IsolationBot, type Bot, type PlayerView, type TileInstance } from 'sg-mahjong-engine';
import { loadTableConfig, loadTableRules } from 'sg-mahjong-engine/node';
import { CoachBot, PolicyBot } from '../bot.js';

const n = Number(process.argv[2] ?? 300);
const cfg = loadTableConfig();
const rules = loadTableRules();

/** Wraps a bot and checks the one thing a bot can get wrong: naming a tile it does not hold. */
class Checked implements Bot {
  constructor(private inner: Bot, private label: string) {}
  chooseDiscard(v: PlayerView): TileInstance {
    const t = this.inner.chooseDiscard(v);
    if (t === undefined || t === null) throw new Error(`${this.label}: chooseDiscard returned nothing (hand ${v.hand.map(kindOf).join(',')})`);
    if (!v.hand.includes(t)) throw new Error(`${this.label}: discarded a tile not in hand (${kindOf(t)} vs ${v.hand.map(kindOf).join(',')})`);
    return t;
  }
  chooseSelfAction(v: PlayerView, o: Parameters<Bot['chooseSelfAction']>[1]) { return this.inner.chooseSelfAction(v, o); }
  chooseClaim(v: PlayerView, o: Parameters<Bot['chooseClaim']>[1]) { return this.inner.chooseClaim(v, o); }
}

const arms: { name: string; make: (rng: () => number) => Bot[] }[] = [
  { name: 'coach x4', make: () => [0, 1, 2, 3].map((i) => new Checked(new CoachBot(), `coach${i}`)) },
  { name: 'model x4', make: () => [0, 1, 2, 3].map((i) => new Checked(new PolicyBot(), `model${i}`)) },
  { name: 'isolation x4', make: (rng) => [0, 1, 2, 3].map((i) => new Checked(new IsolationBot(rng), `iso${i}`)) },
];

for (const arm of arms) {
  let leaks = 0, botErrors = 0, firstLeak = -1;
  const rng = makeRng(11);
  for (let g = 0; g < n; g++) {
    const wall = new Wall(makeRng(11 * 1000003 + g), cfg.unplayable_tiles, rules.jokers.count);
    try {
      const r = playGame(arm.make(rng), cfg, wall, { dealer: g % 4, prevailingWind: Math.floor(g / 4) % 4, rules });
      const total = r.tilesAccounted + wall.totalLeft;
      if (total !== wall.size) { leaks++; if (firstLeak < 0) { firstLeak = g; console.log(`  ${arm.name}: game ${g} accounts for ${total}/${wall.size} (${r.tilesAccounted} + ${wall.totalLeft}), winner ${r.winner}, combo ${r.score?.combination ?? '-'}`); } }
    } catch (e) {
      botErrors++;
      if (botErrors === 1) console.log(`  ${arm.name}: game ${g} threw - ${(e as Error).message}`);
    }
  }
  console.log(`${arm.name.padEnd(14)} ${n} games: ${leaks} tile leaks, ${botErrors} bot errors`);
}
