/**
 * Layer 2 evaluator: for a recorded decision, estimate the value of EVERY legal action by rollouts.
 *
 *   tsx src/evaluate.ts --dir ../data/gen/run-money3 --hands 200 --per-hand 4 --rollouts 32 --mode sampled --policy fast --workers 8 --seed 1
 *
 * Output: <dir>/evals-wN.jsonl.gz, one line per evaluated decision:
 *   { g,h,d,k,seat,bot,sel, mode, policy, n, actions:[{a, ev, sd, win, dealin, draw}], best, regret }
 * EV = mean chips delta for the acting seat at the end of the hand, over n rollouts per action.
 */
import { Worker, parentPort, workerData } from 'node:worker_threads';
import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cpus } from 'node:os';
import { GameState, makeRng, kindOf, type Bot, type RulesConfig } from 'sg-mahjong-engine';
import { rejudge, rolloutBots as solverRolloutBots, type ActionEval, type OutcomeMix } from 'sg-mahjong-solver';
import { positionAt } from './position.js';
import { playHand } from './session.js';
import { makeBot, type RandomnessConfig } from './bots.js';
import { loadHands, eachJsonlGz } from './stats.js';
import { JsonlGzWriter } from './writer.js';
import { rulesForDir } from './tablerules.js';
import type { DecisionRecord, HandRecord } from './records.js';
import { SE_VERSION } from './se.js';

/**
 * Who plays the hand out after the tile under test is thrown. This decides every label in the
 * dataset: an EV means "worth this much IF PLAY CONTINUES LIKE THIS BOT", never "worth this much".
 *
 * `coach` is 120x slower than the rest and cannot grade a whole run - it exists so a small sample
 * can be graded by a bot that plays the same game the positions come from, and compared. The three
 * fast policies all fail at the same thing: a colour hand. They finish one 2-4% of the time where
 * the coach does it 34.6%, so on any position whose best plan is a colour hand they are grading a
 * plan they cannot execute.
 */
export type Policy = 'fast' | 'shanten' | 'efficiency' | 'coach';
export interface EvalArgs { dir: string; hands: number; perHand: number; rollouts: number; mode: 'sampled' | 'oracle'; policy: Policy; seed: number; workers: number; workerIndex: number; rulesOverride: object; randomness: RandomnessConfig; adaptive?: boolean; resume?: boolean; coupled?: boolean; only?: ReadonlySet<string> }
/** The per-action numbers and the outcome mix are the solver's now (`solver/src/rejudge.ts`), so the
 *  phone's Challenge button and this grader share one definition of them. */
export type { ActionEval, OutcomeMix };
export interface EvalRecord { g: number; h: number; d: number; k: string; t: number; seat: number; bot: string; sel: string; mode: string; policy: string; n: number; actions: ActionEval[]; best: string; selEv: number; regret: number }

/**
 * The four bots that play a hand out. The loop itself, the position-keyed coupling that keeps the
 * pairing alive through a claim, and the named policies live in `solver/src/rejudge.ts`; the one
 * policy that is datagen's own - `efficiency`, the personality bot with its randomness - is passed
 * in as a factory.
 */
export function rolloutBots(policy: Policy, seed: number, randomness: RandomnessConfig, coupled = true): Bot[] {
  return solverRolloutBots(policy === 'efficiency' ? (rng) => makeBot('efficiency', rng, randomness) : policy, seed, coupled);
}

/** Evaluate one decision at the given live position. The play-outs are the solver's `rejudge`;
 *  this names the decision so its hidden states are reproducible, and shapes the record. */
export function evaluateDecision(g: GameState, rec: DecisionRecord, a: EvalArgs, rules: RulesConfig): EvalRecord {
  const pending = g.pending()!;
  const seat = pending.seat;
  const judged = rejudge(g.snapshot(), rules, seat, pending.legal, {
    rollouts: a.rollouts, seed: a.seed, key: `${rec.g}:${rec.h}:${rec.d}`,
    policy: a.policy === 'efficiency' ? (rng) => makeBot('efficiency', rng, a.randomness) : a.policy,
    coupled: a.coupled !== false, adaptive: a.adaptive, oracle: a.mode === 'oracle',
  });
  const actions: ActionEval[] = judged.map(({ outcomes: _drop, ...x }) => x);
  actions.sort((x, y) => y.ev - x.ev);
  const selEv = actions.find((x) => x.a === rec.sel)?.ev ?? NaN;
  return { g: rec.g, h: rec.h, d: rec.d, k: rec.k, t: rec.t, seat, bot: rec.bot, sel: rec.sel, mode: a.mode, policy: a.policy, n: a.rollouts, actions, best: actions[0]!.a, selEv, regret: actions[0]!.ev - selEv };
}

/** All decision records of a hand, reconstructed by replaying it (no need to read the decision shards).
 *  Returns null when the replay does not reproduce the recorded hand (hash mismatch) - e.g. the dataset
 *  was generated by an engine with different rules semantics. Callers must skip such hands. */
export function decisionsOfHand(hand: HandRecord, rules: RulesConfig, randomness: RandomnessConfig): DecisionRecord[] | null {
  const out: DecisionRecord[] = [];
  const scoresBefore = hand.scores.map((s, i) => s - hand.delta[i]!);
  const { record } = playHand({ sessionId: hand.g, handIdx: hand.h, seed: hand.seed, dealer: hand.dl, prevailingWind: hand.w, botTypes: hand.bots, scores: scoresBefore, seq: hand.seq }, rules, randomness, { decision: (r) => out.push(r), hand: () => {} }, true);
  if (record.hash !== hand.hash || record.winner !== hand.winner || record.turns !== hand.turns) return null;
  return out;
}

/**
 * Pick decisions to evaluate: `hands` sampled hands (deterministic), `perHand` decisions each, only
 * decisions with a real choice.
 *
 * `a.only` overrides all of that and grades exactly the listed decisions, keyed `g:h:d`.
 *
 * It exists because the expensive graders are ruinously slow and most decisions are not worth their
 * time. Only about 4% of decisions come out with a best action the play-outs can separate, and those
 * are the only ones any comparison can use - the rest are ties, where two graders disagree simply
 * because there is nothing to agree about. Grading cheaply first, keeping the decisions that came
 * out clear, and spending the slow grader ONLY on those turns an eight-hour run worth 58 usable
 * comparisons into one worth about 1,400.
 *
 * It is also the right population rather than merely the affordable one: the quiz picks its
 * questions by exactly this test, so "positions the shipped grader is sure about" is the set we
 * actually care about agreeing on.
 */
export function selectDecisions(dir: string, a: EvalArgs, rules: RulesConfig): { hand: HandRecord; decisions: DecisionRecord[] }[] {
  if (a.only) return selectListed(dir, a, rules, a.only);
  const hands = loadHands(dir).filter((_, i) => i % a.workers === a.workerIndex);
  const rng = makeRng(a.seed + a.workerIndex);
  const chosen = new Map<string, HandRecord>();
  const quota = Math.ceil(a.hands / a.workers);
  while (chosen.size < Math.min(quota, hands.length)) { const h = hands[Math.floor(rng() * hands.length)]!; chosen.set(`${h.g}:${h.h}`, h); }
  const out: { hand: HandRecord; decisions: DecisionRecord[] }[] = [];
  let drifted = 0;
  for (const hand of chosen.values()) {
    const all = decisionsOfHand(hand, rules, a.randomness);
    if (!all) { drifted++; continue; }
    const pool = all.filter((d) => d.legal.length > 1);
    const pick: DecisionRecord[] = [];
    while (pick.length < a.perHand && pool.length) pick.push(pool.splice(Math.floor(rng() * pool.length), 1)[0]!);
    pick.sort((x, y) => x.d - y.d);
    out.push({ hand, decisions: pick });
  }
  if (drifted) console.error(`[w${a.workerIndex}] ${drifted} hands did not replay under the current engine and were skipped`);
  return out;
}

/** Grade exactly the decisions named in `only`, sharded across workers by hand. */
function selectListed(dir: string, a: EvalArgs, rules: RulesConfig, only: ReadonlySet<string>): { hand: HandRecord; decisions: DecisionRecord[] }[] {
  const wanted = new Map<string, Set<number>>();
  for (const key of only) {
    const bits = key.split(':');
    if (bits.length !== 3) throw new Error(`bad decision key ${key}, expected g:h:d`);
    const hk = `${bits[0]}:${bits[1]}`;
    (wanted.get(hk) ?? wanted.set(hk, new Set()).get(hk)!).add(Number(bits[2]));
  }
  const hands = loadHands(dir).filter((x) => wanted.has(`${x.g}:${x.h}`));
  const mine = hands.filter((_, i) => i % a.workers === a.workerIndex);
  const out: { hand: HandRecord; decisions: DecisionRecord[] }[] = [];
  let drifted = 0, missing = 0;
  for (const hand of mine) {
    const all = decisionsOfHand(hand, rules, a.randomness);
    if (!all) { drifted++; continue; }
    const want = wanted.get(`${hand.g}:${hand.h}`)!;
    const pick = all.filter((d) => want.has(d.d));
    missing += want.size - pick.length;
    if (pick.length) out.push({ hand, decisions: pick.sort((x, y) => x.d - y.d) });
  }
  if (drifted) console.error(`[w${a.workerIndex}] ${drifted} listed hands did not replay and were skipped`);
  if (missing) console.error(`[w${a.workerIndex}] ${missing} listed decisions were not found in their hand`);
  return out;
}

export function runEvalWorker(a: EvalArgs, progress?: (n: number) => void): { evaluated: number; skipped: number; errors: number } {
  const rules = rulesForDir(a.dir, a.rulesOverride);
  const path = join(a.dir, `evals-w${a.workerIndex}.jsonl.gz`);
  // --resume: skip decisions already on disk (selection is deterministic, so the same worker sees the same hands)
  const done = new Set<string>();
  if (a.resume && existsSync(path)) eachJsonlGz<EvalRecord>(path, (e) => done.add(`${e.g}:${e.h}:${e.d}`));   // stream: a worker's own shard is gigabytes once parsed
  const out = new JsonlGzWriter(path, 1 << 20, a.resume);
  let n = 0, skipped = 0, errors = 0;
  for (const { hand, decisions } of selectDecisions(a.dir, a, rules)) {
    for (const dec of decisions) {
      if (done.has(`${dec.g}:${dec.h}:${dec.d}`)) { skipped++; continue; }
      try {
        const pos = positionAt(hand, dec.d, rules, a.randomness);
        if (!pos) continue;
        // sanity: the reconstructed visible hand must match the record
        const hk = pos.g.players[pos.g.pending()!.seat]!.hand.map(kindOf).sort((x, y) => x - y).join(',');
        if (hk !== [...dec.me.h].sort((x, y) => x - y).join(',')) throw new Error(`position mismatch at ${dec.g}:${dec.h}:${dec.d}`);
        out.write(evaluateDecision(pos.g, dec, a, rules)); n++; progress?.(n);
      } catch (e) {
        errors++; console.error(`[w${a.workerIndex}] decision ${dec.g}:${dec.h}:${dec.d} (${dec.k}) failed: ${(e as Error).message}`);
        if (errors > 50) throw e;            // something systematic: stop this worker
      }
    }
  }
  out.close();
  return { evaluated: n, skipped, errors };
}

if (parentPort) {
  const a = workerData as EvalArgs;
  const res = runEvalWorker(a, (n) => parentPort!.postMessage({ type: 'progress', n }));
  parentPort.postMessage({ type: 'done', ...res });
} else if (process.argv[1] && /evaluate\.(ts|js)$/.test(process.argv[1])) {
  const arg = (name: string, def?: string) => { const i = process.argv.indexOf(`--${name}`); return i >= 0 ? (process.argv[i + 1] ?? 'true') : def; };
  const dir = arg('dir', '../data/gen/dev')!;
  const workers = Number(arg('workers', String(Math.max(1, Math.min(8, cpus().length - 1)))));
  const base: Omit<EvalArgs, 'workerIndex'> = {
    dir, hands: Number(arg('hands', '50')), perHand: Number(arg('per-hand', '4')), rollouts: Number(arg('rollouts', '32')),
    mode: (arg('mode', 'sampled') as 'sampled' | 'oracle'), policy: (arg('policy', 'shanten') as Policy), seed: Number(arg('seed', '1')), workers, adaptive: process.argv.includes('--adaptive'), resume: process.argv.includes('--resume'),
    // --only <file>: one `g:h:d` per line, grade exactly those and nothing else
    only: arg('only') ? new Set(readFileSync(arg('only')!, 'utf8').split('\n').map((l) => l.trim()).filter(Boolean)) : undefined,
    coupled: !process.argv.includes('--no-coupled'),   // position-keyed rollout randomness; --no-coupled reproduces pre-2026-08-26 runs
    rulesOverride: arg('rules') ? JSON.parse(arg('rules')!) : {}, randomness: arg('randomness') ? JSON.parse(arg('randomness')!) : { ranked: [0.7, 0.15, 0.1], random: 0.05 },
  };
  mkdirSync(dir, { recursive: true });
  const t0 = Date.now(); let remaining = workers, total = 0; const prog = new Array<number>(workers).fill(0);
  for (let i = 0; i < workers; i++) {
    const w = new Worker(fileURLToPath(import.meta.url), { workerData: { ...base, workerIndex: i } });
    let totalSkipped = 0, totalErrors = 0, failedWorkers = 0;
    const finishIfDone = () => {
      if (--remaining !== 0) return;
      const s = (Date.now() - t0) / 1000;
      writeFileSync(join(dir, 'evals-manifest.json'), JSON.stringify({ ...base, seVersion: SE_VERSION, total, skipped: totalSkipped, errors: totalErrors, failedWorkers, seconds: s }, null, 2));
      console.log(`\n${total} decisions evaluated in ${s.toFixed(0)}s (${(total / s).toFixed(2)}/s), ${totalSkipped} skipped (resume), ${totalErrors} errors, ${failedWorkers} failed workers -> ${dir}/evals-w*.jsonl.gz`);
    };
    w.on('message', (m: { type: string; n?: number; evaluated?: number; skipped?: number; errors?: number }) => {
      if (m.type === 'progress') { prog[i] = m.n!; const tot = prog.reduce((x, y) => x + y, 0); if (process.stdout.isTTY) process.stdout.write(`\r${tot} decisions evaluated`); else if (tot % 50 === 0) console.log(`${tot} decisions evaluated`); }
      if (m.type === 'done') { total += m.evaluated!; totalSkipped += m.skipped ?? 0; totalErrors += m.errors ?? 0; finishIfDone(); }
    });
    w.on('error', (e) => { console.error(`worker ${i} failed:`, e); failedWorkers++; finishIfDone(); });   // other workers keep going; rerun with --resume
  }
}
