/**
 * Opponent reading tables: what public signals actually tell you about a hidden hand.
 *
 *   tsx src/reads.ts --dir ../data/gen/run-money3 --hands 20000 --out ../web/public/reads --name money
 *
 * Replays recorded hands and, at sampled moments, compares what is PUBLIC about each seat
 * (exposed melds, their discard pattern, the turn) with what they are TRULY holding
 * (shanten, the exact tiles they would win on). Aggregated into probability tables.
 *
 * `--coach N` plays N fresh hands with four CoachBots instead of replaying a recorded run. The
 * recorded runs were generated by the datagen personalities, which have no colour target at all and
 * win a colour hand 1.3% of the time; a table of coaches wins one 32% of the time. A read about
 * suits measured on the first population is measured on a game nobody at this table is playing.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  GameState, Wall, makeRng, tableConfigOf, kindOf, isHonour, isSuited, isJoker, isTerminal, suitOf,
  countsAndJokers, shanten, winningKinds, type TileKind,
} from 'sg-mahjong-engine';
import { loadHands } from './stats.js';
import { rulesForDir } from './tablerules.js';
import { botsFor } from './position.js';
import { DEFAULT_RANDOMNESS } from './bots.js';
import { CoachBot } from 'sg-mahjong-solver';
import type { Bot } from 'sg-mahjong-engine';

function arg(n: string, d?: string) { const i = process.argv.indexOf(`--${n}`); return i >= 0 ? (process.argv[i + 1] ?? d) : d; }
const dir = arg('dir', '../data/gen/run-money3')!;
const outDir = arg('out', '../web/public/reads')!;
const name = arg('name', 'money')!;
const maxHands = Number(arg('hands', '20000'));
const every = Number(arg('every', '3'));      // sample every Nth discard decision
const coachHands = Number(arg('coach', '0')); // play this many fresh coach hands instead of replaying

const rules = rulesForDir(dir);
const cfg = tableConfigOf(rules);
const bucket = (turn: number) => Math.min(60, Math.floor(turn / 10) * 10);   // 0,10,...,60
const tileClass = (k: TileKind) => isJoker(k) ? 'joker' : isHonour(k) ? 'honour' : isTerminal(k) ? 'terminal' : 'simple';

interface Cell { n: number; hit: number }
const table = () => ({} as Record<string, Cell>);
const bump = (t: Record<string, Cell>, key: string, hit: boolean) => { const c = (t[key] ??= { n: 0, hit: 0 }); c.n++; if (hit) c.hit++; };

const ready = table();        // "melds|turn"        -> is that seat one tile away?
const suitTell = table();     // "ownSuitDiscards|turn" -> are they really collecting that suit?
const danger = table();       // "class|turn"        -> would discarding it have dealt in to someone?
const dangerSafe = table();   // "class|turn|seenBefore" -> same, split by whether the tile was already discarded
const honourTiming = table(); // "turn"              -> P(an honour discard is claimed)
/**
 * "class|turn|seen|walled" -> same as dangerSafe, split by whether every RUN that could contain
 * this tile is already impossible.
 *
 * A tile completes a run three ways - as the bottom, the middle or the top - and each way needs two
 * specific neighbours. When all four copies of one of those neighbours are already accounted for,
 * that way is dead. When all three ways are dead the tile can only be hit by a pair wait or a lone
 * tile wait, which are far rarer. This is `no_chance_tiles` from the tactics book, and the coach
 * currently cannot see it at all: its danger model knows only the tile's class, how late it is, and
 * whether one has been thrown.
 */
const dangerWall = table();
/**
 * "class|turn|seen|<none|off|in>" -> the same deal-in question, split by what the opponents have
 * MELDED rather than by how many times they have melded.
 *
 * The coach's whole threat model is a count: three exposed sets means fear, none means relax. A
 * dragon pong and a chow of 3-4-5 are the same input to it. The tactics book spends eleven tips on
 * the other half of that - `half_color_tell` calls the suit an opponent is collecting "the
 * strongest single read available" - and the mechanical version is this. A player assembling one
 * suit does not throw that suit away, so when every suited set they have exposed is in the same
 * suit AND they have barely discarded it, that suit is their hand.
 *
 * Three tags per candidate tile: `none` when no opponent shows any concentration, `in` when the
 * tile is in a suit somebody is concentrating in, `off` when somebody is concentrating and this
 * tile is outside it. `off` is the cell that matters - a read is only worth pricing if it also
 * says what is SAFE.
 *
 * Measured at two strictnesses because how much exposure counts as a tell is the open question:
 * `dangerMeld2` needs two exposed sets in the suit, `dangerMeld1` accepts one.
 */
const dangerMeld2 = table();
const dangerMeld1 = table();
/**
 * The same question asked PER OPPONENT, which is the only way it can be answered honestly.
 *
 * "Does this tile deal in to anybody" pools three seats, so a read about one of them is diluted by
 * two who have nothing to do with it - and worse, melding takes tiles off the table, so a suit
 * somebody has two sets in is a suit the OTHER two are less likely to be waiting on. That confound
 * points the wrong way and is big enough to swamp the effect being looked for.
 *
 * Keyed "<class>|<turn>|<plain|off|in>" where the tag is about THIS opponent only: `in` when the
 * tile is in the suit they are concentrating in, `off` when they are concentrating and it is not,
 * `plain` when they show no concentration at all.
 */
const oppMeld2 = table();
const oppMeld1 = table();
/** Is the tell true? "<minMelds>" -> what the concealed part of a flagged seat actually holds. */
const tellPrecision = table();
/**
 * `dangerSafe` under the definition of "already seen" that the COACH actually uses.
 *
 * The table splits fresh from seen on the discard pool alone. `rank.ts` looks the answer up with
 * `ctx.visible`, which is the discard pool PLUS every exposed meld - so a tile whose only copies sit
 * in somebody's chow is `fresh` to the measurement and `seen` to the coach, and it is priced off a
 * cell that was never measured for it. Melded copies are two thirds invisible to the pool: a chow
 * claimed on 4 tong shows the 4 in the discard log and hides the 3 and the 5.
 *
 * Same key as `dangerSafe` so the two are read side by side. If the discount holds under both
 * definitions the mismatch is harmless; if it does not, the coach has been reading the wrong cell.
 */
const dangerVisible = table();
let sampled = 0, hands = 0;

/**
 * Which suit, if any, this seat is visibly collecting - from public information only.
 *
 * Half-Color is one suit plus honours, so honour melds do not break the pattern; a set in a second
 * suit does. The discard test is the other half and does the real work: anybody can be dealt two
 * sets of one suit, but a player who has thrown that suit away is not collecting it.
 */
function concentratedSuit(melds: readonly { tiles: TileKind[] }[], discards: readonly number[], minMelds: number): string | null {
  const suited = melds.filter((m) => isSuited(m.tiles[0]!));
  if (suited.length < minMelds) return null;
  const s = suitOf(suited[0]!.tiles[0]!);
  if (!s || !suited.every((m) => suitOf(m.tiles[0]!) === s)) return null;
  if (discards.filter((t) => suitOf(kindOf(t)) === s).length > 1) return null;
  return s;
}

/** The hands to walk: either the recorded run, or fresh ones the coach plays against itself. */
function* sources(): Generator<{ g: GameState; bots: Bot[] }> {
  if (coachHands > 0) {
    for (let i = 0; i < coachHands; i++) {
      const wall = new Wall(makeRng(coachSeed * 1000003 + i), cfg.unplayable_tiles, rules.jokers.count);
      yield {
        g: GameState.deal(cfg, wall, { dealer: i % 4, prevailingWind: Math.floor(i / 4) % 4, rules }),
        bots: [0, 1, 2, 3].map(() => new CoachBot()),
      };
    }
    return;
  }
  for (const hr of loadHands(dir).slice(0, maxHands)) {
    yield {
      g: GameState.deal(cfg, new Wall(makeRng(hr.seed), rules.unplayable_tiles, rules.jokers.count), { dealer: hr.dl, prevailingWind: hr.w, rules }),
      bots: botsFor(hr, DEFAULT_RANDOMNESS),
    };
  }
}
const coachSeed = Number(arg('seed', '11'));
for (const { g, bots } of sources()) {
  let step = 0, guard = 0;
  hands++;
  while (!g.finished && guard++ < 3000) {
    g.advance();
    const p = g.pending();
    if (p && p.kind === 'discard' && step++ % every === 0) {
      sampled++;
      const turn = bucket(g.playerTurns);
      // what every seat is really holding, and what is public about them
      const truth = g.players.map((q) => {
        const kinds = q.hand.map(kindOf);
        const std = kinds.filter((k) => !isJoker(k));
        const sh = shanten(kinds, q.melds.length);
        const cj = countsAndJokers(kinds);
        const outs = sh === 0 && kinds.length % 3 === 1 ? winningKinds(cj.counts, 4 - q.melds.length) : [];
        return { sh, outs: new Set(outs), kinds, std };
      });
      for (let s = 0; s < 4; s++) {
        const q = g.players[s]!, t = truth[s]!;
        bump(ready, `${Math.min(3, q.melds.length)}|${turn}`, t.sh <= 0);
        // the suit tell: how many tiles of each suit have THEY discarded, vs what they actually hold
        for (const suit of ['wan', 'tong', 'sok'] as const) {
          const thrown = q.discards.filter((x) => suitOf(kindOf(x)) === suit).length;
          const holding = t.std.filter((k) => suitOf(k) === suit).length + q.melds.filter((m) => suitOf(m.tiles[0]!) === suit).length * 3;
          bump(suitTell, `${Math.min(3, thrown)}|${turn}`, holding >= 7);       // 7+ tiles = genuinely collecting it
        }
      }
      // danger: for each tile the acting player could throw, would it complete somebody?
      const me = p.seat;
      const seen = new Set(g.discardLog.map((e) => kindOf(e.tile)));
      // what `ctx.visible` gives the coach: the pool plus every exposed meld that is not its own
      const visible = new Set<TileKind>(seen);
      for (let s = 0; s < 4; s++) if (s !== me) for (const m of g.players[s]!.melds) for (const t of m.tiles) visible.add(t);
      // Copies of each kind THIS PLAYER can account for: their own hand, every exposed meld, and
      // the discards that were not claimed (a claimed one is already counted inside its meld).
      const accounted = new Uint8Array(34);
      for (const e of g.discardLog) if (e.claimedBy === null) { const kk = kindOf(e.tile); if (kk < 34) accounted[kk]!++; }
      for (let s = 0; s < 4; s++) for (const m of g.players[s]!.melds) for (const t of m.tiles) if (t < 34) accounted[t]!++;
      for (const t of g.players[me]!.hand) { const kk = kindOf(t); if (kk < 34) accounted[kk]!++; }
      const walled = (k: TileKind): boolean => {
        if (!isSuited(k)) return false;                       // honours are never part of a run
        const r = (k % 9) + 1, base = k - (r - 1);
        const alive = (rank: number) => accounted[base + rank - 1]! < 4;
        const pairs: [number, number][] = [[r - 2, r - 1], [r - 1, r + 1], [r + 1, r + 2]];
        return !pairs.some(([a, b]) => a >= 1 && a <= 9 && b >= 1 && b <= 9 && alive(a) && alive(b));
      };
      // which suits the OTHER three seats are visibly collecting, at both strictnesses
      const threat2 = new Set<string>(), threat1 = new Set<string>();
      for (let s = 0; s < 4; s++) {
        if (s === me) continue;
        const q = g.players[s]!;
        const c2 = concentratedSuit(q.melds, q.discards, 2); if (c2) threat2.add(c2);
        const c1 = concentratedSuit(q.melds, q.discards, 1); if (c1) threat1.add(c1);
      }
      const tagOf = (k: TileKind, threat: Set<string>) => {
        if (!threat.size) return 'none';
        const s = suitOf(k);
        return s && threat.has(s) ? 'in' : 'off';
      };
      // per-opponent: what THIS seat has exposed, and whether the tell about them is even true
      const opps: { seat: number; c2: string | null; c1: string | null }[] = [];
      for (let s = 0; s < 4; s++) {
        if (s === me) continue;
        const q = g.players[s]!;
        const c2 = concentratedSuit(q.melds, q.discards, 2), c1 = concentratedSuit(q.melds, q.discards, 1);
        opps.push({ seat: s, c2, c1 });
        const t = truth[s]!;
        // The melds are not evidence about the CONCEALED part - two chows already supply six tiles
        // of the suit, so "holds 7+ counting melds" is true by construction and says nothing. The
        // question is whether the part you cannot see is in that suit too.
        const concealedIn = (suit: string) => t.std.filter((k) => suitOf(k) === suit).length;
        const concealedSuited = t.std.filter(isSuited).length;
        const purity = (suit: string) => concealedSuited > 0 && concealedIn(suit) / concealedSuited >= 0.8;
        if (c2) { bump(tellPrecision, '2|five', concealedIn(c2) >= 5); bump(tellPrecision, '2|pure', purity(c2)); }
        if (c1) { bump(tellPrecision, '1|five', concealedIn(c1) >= 5); bump(tellPrecision, '1|pure', purity(c1)); }
      }
      const oppTag = (k: TileKind, c: string | null) => (!c ? 'plain' : suitOf(k) === c ? 'in' : 'off');
      for (const act of p.legal) {
        if (act.a !== 'discard') continue;
        const k = act.kind;
        for (const o of opps) {
          const hit = truth[o.seat]!.sh === 0 && truth[o.seat]!.outs.has(k);
          bump(oppMeld2, `${tileClass(k)}|${turn}|${seen.has(k) ? 'seen' : 'fresh'}|${oppTag(k, o.c2)}`, hit);
          bump(oppMeld1, `${tileClass(k)}|${turn}|${seen.has(k) ? 'seen' : 'fresh'}|${oppTag(k, o.c1)}`, hit);
        }
        const deadly = truth.some((t, s) => s !== me && t.sh === 0 && t.outs.has(k));
        const fresh = seen.has(k) ? 'seen' : 'fresh';
        bump(danger, `${tileClass(k)}|${turn}`, deadly);
        bump(dangerSafe, `${tileClass(k)}|${turn}|${fresh}`, deadly);
        bump(dangerVisible, `${tileClass(k)}|${turn}|${visible.has(k) ? 'seen' : 'fresh'}`, deadly);
        if (isSuited(k)) bump(dangerWall, `${tileClass(k)}|${turn}|${fresh}|${walled(k) ? 'walled' : 'open'}`, deadly);
        bump(dangerMeld2, `${tileClass(k)}|${turn}|${fresh}|${tagOf(k, threat2)}`, deadly);
        bump(dangerMeld1, `${tileClass(k)}|${turn}|${fresh}|${tagOf(k, threat1)}`, deadly);
        if (isHonour(k)) bump(honourTiming, `${turn}`, deadly);
      }
    }
    if (g.finished) break;
    g.step(bots);
  }
}

mkdirSync(outDir, { recursive: true });
const pct = (t: Record<string, Cell>) => Object.fromEntries(Object.entries(t).filter(([, c]) => c.n >= 30).map(([k, c]) => [k, { p: c.hit / c.n, n: c.n }]));
writeFileSync(join(outDir, `${name}.json`), JSON.stringify({ run: coachHands > 0 ? `coach-seed${coachSeed}` : dir.split('/').pop(), hands, sampled, ready: pct(ready), suitTell: pct(suitTell), danger: pct(danger), dangerSafe: pct(dangerSafe), dangerVisible: pct(dangerVisible), dangerWall: pct(dangerWall), dangerMeld2: pct(dangerMeld2), dangerMeld1: pct(dangerMeld1), oppMeld2: pct(oppMeld2), oppMeld1: pct(oppMeld1) }));
console.log(`reads: ${hands} hands, ${sampled} sampled moments -> ${outDir}/${name}.json`);
const show = (label: string, t: Record<string, Cell>, keys: string[]) => {
  console.log(`\n${label}`);
  for (const k of keys) { const c = t[k]; if (c && c.n >= 30) console.log(`  ${k.padEnd(22)} ${(100 * c.hit / c.n).toFixed(0).padStart(3)}%   (n=${c.n})`); }
};
show('P(seat is one tile away)  melds|turn', ready, ['0|10', '0|30', '0|50', '1|30', '2|30', '3|30', '3|40', '3|50']);
show('P(they are really collecting a suit)  ownDiscardsOfThatSuit|turn', suitTell, ['0|20', '1|20', '2|20', '3|20', '0|40', '1|40', '2|40', '3|40']);
show('P(discarding this deals in)  tileClass|turn', danger, ['honour|10', 'honour|30', 'honour|50', 'terminal|30', 'simple|30', 'simple|50', 'joker|30']);
show('...split by whether the tile was already discarded once', dangerSafe, ['simple|40|fresh', 'simple|40|seen', 'honour|40|fresh', 'honour|40|seen']);
// The question this run exists to answer: is a tile whose runs are all dead measurably safer?
{
  console.log('\nP(deals in) with every run containing it already impossible  class|turn|seen|walled');
  const rows: string[] = [];
  for (const cls of ['simple', 'terminal']) for (const t of [20, 30, 40, 50]) for (const f of ['fresh', 'seen']) {
    const open = dangerWall[`${cls}|${t}|${f}|open`], wall = dangerWall[`${cls}|${t}|${f}|walled`];
    if (!open || !wall || open.n < 30 || wall.n < 30) continue;
    const o = open.hit / open.n, w = wall.hit / wall.n;
    rows.push(`  ${cls}|${t}|${f}`.padEnd(24) + `open ${(100 * o).toFixed(2)}%  walled ${(100 * w).toFixed(2)}%   x${(w / Math.max(1e-9, o)).toFixed(2)}   (n=${open.n}/${wall.n})`);
  }
  console.log(rows.length ? rows.join('\n') : '  (no cell had 30 of each - walled tiles are rarer than that at this sample size)');
}
// The question this run exists to answer: does WHAT an opponent melded change which tiles are safe?
//
// The comparison that means something is `in` against `off`, not either against `none`. Both of
// those are drawn from positions where somebody IS concentrating, so opponent development is held
// fixed and only the tile moves. Against `none` the count and the content are mixed together, and
// the count is already priced by `ready`.
{
  const z = (a: Cell, b: Cell) => {
    const pa = a.hit / a.n, pb = b.hit / b.n;
    const se = Math.sqrt(pa * (1 - pa) / a.n + pb * (1 - pb) / b.n);
    return se > 0 ? (pa - pb) / se : 0;
  };
  for (const [label, t] of [['two exposed sets in the suit', dangerMeld2], ['one exposed set in the suit', dangerMeld1]] as const) {
    console.log(`\nP(deals in) IN their suit vs OUTSIDE it - ${label}`);
    const rows: string[] = [];
    const pool = { in: { n: 0, hit: 0 }, off: { n: 0, hit: 0 }, none: { n: 0, hit: 0 } };
    for (const cls of ['simple', 'terminal']) for (const f of ['fresh', 'seen']) {
      const acc = { in: { n: 0, hit: 0 }, off: { n: 0, hit: 0 }, none: { n: 0, hit: 0 } };
      for (const tn of [20, 30, 40, 50]) for (const tag of ['none', 'off', 'in'] as const) {
        const c = t[`${cls}|${tn}|${f}|${tag}`]; if (!c) continue;
        acc[tag].n += c.n; acc[tag].hit += c.hit;
        pool[tag].n += c.n; pool[tag].hit += c.hit;
      }
      if (acc.in.n < 200 || acc.off.n < 200) continue;
      const pc = (c: Cell) => `${(100 * c.hit / c.n).toFixed(2)}%`;
      rows.push(`  ${cls}|${f}`.padEnd(20)
        + `in ${pc(acc.in)}  off ${pc(acc.off)}   x${((acc.in.hit / acc.in.n) / Math.max(1e-9, acc.off.hit / acc.off.n)).toFixed(2)}`
        + `  z=${z(acc.in, acc.off).toFixed(2)}   (n=${acc.in.n}/${acc.off.n})`);
    }
    console.log(rows.length ? rows.join('\n') : '  (no cell had the sample for it)');
    const pc = (c: Cell) => `${(100 * c.hit / c.n).toFixed(3)}%`;
    console.log(`  pooled over suited tiles:  in ${pc(pool.in)}  off ${pc(pool.off)}  none ${pc(pool.none)}`
      + `   in/off x${((pool.in.hit / pool.in.n) / Math.max(1e-9, pool.off.hit / pool.off.n)).toFixed(2)}  z=${z(pool.in, pool.off).toFixed(2)}`);
    const tot = (tag: string) => Object.entries(t).filter(([k]) => k.endsWith(`|${tag}`)).reduce((a, [, c]) => a + c.n, 0);
    const all = tot('none') + tot('off') + tot('in');
    console.log(`  how often each applies:  none ${(100 * tot('none') / all).toFixed(1)}%   off ${(100 * tot('off') / all).toFixed(1)}%   in ${(100 * tot('in') / all).toFixed(1)}%`);
  }
}

// The same read, per opponent, which is where the confound above disappears.
{
  const z = (a: Cell, b: Cell) => {
    const pa = a.hit / a.n, pb = b.hit / b.n;
    const se = Math.sqrt(pa * (1 - pa) / a.n + pb * (1 - pb) / b.n);
    return se > 0 ? (pa - pb) / se : 0;
  };
  for (const [label, t] of [['two exposed sets', oppMeld2], ['one exposed set', oppMeld1]] as const) {
    console.log(`\nP(deals in TO THAT SEAT) in their suit vs outside it - ${label}`);
    const pool = { in: { n: 0, hit: 0 }, off: { n: 0, hit: 0 }, plain: { n: 0, hit: 0 } };
    const rows: string[] = [];
    for (const f of ['fresh', 'seen']) for (const tn of [20, 30, 40, 50]) {
      const acc = { in: { n: 0, hit: 0 }, off: { n: 0, hit: 0 }, plain: { n: 0, hit: 0 } };
      for (const cls of ['simple', 'terminal']) for (const tag of ['plain', 'off', 'in'] as const) {
        const c = t[`${cls}|${tn}|${f}|${tag}`]; if (!c) continue;
        acc[tag].n += c.n; acc[tag].hit += c.hit; pool[tag].n += c.n; pool[tag].hit += c.hit;
      }
      if (acc.in.n < 200 || acc.off.n < 200) continue;
      const pc = (c: Cell) => `${(100 * c.hit / c.n).toFixed(2)}%`;
      rows.push(`  ${f} turn ${String(tn).padEnd(8)}in ${pc(acc.in)}  off ${pc(acc.off)}  plain ${pc(acc.plain)}`
        + `   in/off x${((acc.in.hit / acc.in.n) / Math.max(1e-9, acc.off.hit / acc.off.n)).toFixed(2)}`
        + `  z=${z(acc.in, acc.off).toFixed(2)}   (n=${acc.in.n}/${acc.off.n})`);
    }
    console.log(rows.length ? rows.join('\n') : '  (no cell had the sample for it)');
    const pc = (c: Cell) => `${(100 * c.hit / c.n).toFixed(3)}%`;
    console.log(`  pooled:  in ${pc(pool.in)}  off ${pc(pool.off)}  plain ${pc(pool.plain)}`
      + `   in/off x${((pool.in.hit / pool.in.n) / Math.max(1e-9, pool.off.hit / pool.off.n)).toFixed(2)}  z=${z(pool.in, pool.off).toFixed(2)}`);
  }
  console.log('\nis the tell even true?  what the CONCEALED part of a flagged seat actually holds');
  for (const k of ['1', '2']) {
    const five = tellPrecision[`${k}|five`], pure = tellPrecision[`${k}|pure`];
    if (five && pure) console.log(`  ${k} exposed set${k === '1' ? ' ' : 's'} in the suit:`
      + `  5+ concealed of it ${(100 * five.hit / five.n).toFixed(1)}%`
      + `   80%+ of their concealed suited tiles ${(100 * pure.hit / pure.n).toFixed(1)}%   (n=${five.n})`);
  }
}

// Does the fresh/seen discount survive the definition the coach actually looks it up with?
{
  console.log('\n"already seen" measured on the discard pool (the table) vs on everything visible (the coach)');
  const rows: string[] = [];
  for (const cls of ['simple', 'terminal', 'honour']) for (const tn of [20, 30, 40, 50]) {
    const a = dangerSafe[`${cls}|${tn}|fresh`], b = dangerSafe[`${cls}|${tn}|seen`];
    const c = dangerVisible[`${cls}|${tn}|fresh`], d = dangerVisible[`${cls}|${tn}|seen`];
    if (!a || !b || !c || !d || Math.min(a.n, b.n, c.n, d.n) < 200) continue;
    const p = (x: Cell) => `${(100 * x.hit / x.n).toFixed(2)}%`;
    const gap = (x: Cell, y: Cell) => `x${((y.hit / y.n) / Math.max(1e-9, x.hit / x.n)).toFixed(2)}`;
    rows.push(`  ${cls}|${tn}`.padEnd(18)
      + `pool: fresh ${p(a)} seen ${p(b)} ${gap(a, b)}`.padEnd(38)
      + `visible: fresh ${p(c)} seen ${p(d)} ${gap(c, d)}`);
  }
  console.log(rows.join('\n'));
}
