#!/bin/bash
# Regenerate prototype/app.html — a runnable snapshot of the CURRENT build, one file, no server.
#
# Changs decided on 2026-09-12 that the prototype is the current build rather than a historical
# artefact, and that new work is prototyped here before production code is written. This script is
# how the snapshot is kept true. app.html is git-ignored because it is 7MB of generated bytes that
# change wholesale on every build; the launchpads beside it are committed and hand-maintained.
set -e
cd "$(dirname "$0")/../web"
V=$(ls -d ../node_modules/.pnpm/vite@5*/node_modules/vite/bin/vite.js | head -1)
SINGLE_FILE=1 node "$V" build >/dev/null
node tools/singlefile.mjs --questions 500 --hands 30 --out ../prototype/app.html
node "$V" build >/dev/null     # leave dist/ as the normal split build again
echo "prototype/app.html rebuilt from the current source"
